FROM node:20-alpine

RUN apk update && apk add --no-cache \
    build-base gcc autoconf automake \
    zlib-dev libpng-dev vips-dev git python3

WORKDIR /app
ENV NODE_ENV=development

COPY package*.json ./
RUN npm install --legacy-peer-deps

COPY . .

EXPOSE 1337
CMD ["npm", "run", "develop"]
